version: "3.9"
services:
 db:
  image: postgres
  restart: always
  environment:
   TZ: Asia/Seoul
   POSTGRES_USER: postgres 
   POSTGRES_PASSWORD: example
  ports: 
   - "5432:5432"
  volumes:
   - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
